name: Walmart-Clone-Web Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 14
      - run: yarn --version
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
